2021-05-14 11:12:46,023 INFO    ScriptRunner.scriptThread:16666 [wandb_setup.py:_flush():69] setting env: {}
2021-05-14 11:12:46,024 INFO    ScriptRunner.scriptThread:16666 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-14 11:12:46,024 INFO    ScriptRunner.scriptThread:16666 [wandb_init.py:_log_setup():336] Logging user logs to /Users/giftyarthur/thesis-streamlit/wandb/run-20210514_111246-1qa9w7ds/logs/debug.log
2021-05-14 11:12:46,025 INFO    ScriptRunner.scriptThread:16666 [wandb_init.py:_log_setup():337] Logging internal logs to /Users/giftyarthur/thesis-streamlit/wandb/run-20210514_111246-1qa9w7ds/logs/debug-internal.log
2021-05-14 11:12:46,025 INFO    ScriptRunner.scriptThread:16666 [wandb_init.py:init():369] calling init triggers
2021-05-14 11:12:46,025 INFO    ScriptRunner.scriptThread:16666 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-14 11:12:46,025 INFO    ScriptRunner.scriptThread:16666 [wandb_init.py:init():418] starting backend
2021-05-14 11:12:46,025 INFO    ScriptRunner.scriptThread:16666 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-14 11:12:46,089 INFO    ScriptRunner.scriptThread:16666 [backend.py:ensure_launched():132] starting backend process...
2021-05-14 11:12:46,147 INFO    ScriptRunner.scriptThread:16666 [backend.py:ensure_launched():137] started backend process with pid: 16683
2021-05-14 11:12:46,154 INFO    ScriptRunner.scriptThread:16666 [wandb_init.py:init():423] backend started and connected
2021-05-14 11:12:46,183 INFO    ScriptRunner.scriptThread:16666 [wandb_init.py:init():465] updated telemetry
2021-05-14 11:12:46,191 INFO    ScriptRunner.scriptThread:16666 [wandb_init.py:init():484] communicating current version
2021-05-14 11:12:51,200 INFO    ScriptRunner.scriptThread:16666 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-14 11:12:51,625 INFO    ScriptRunner.scriptThread:16666 [wandb_init.py:init():522] starting run threads in backend
2021-05-14 11:12:54,986 INFO    ScriptRunner.scriptThread:16666 [wandb_run.py:_console_start():1565] atexit reg
2021-05-14 11:12:54,988 INFO    ScriptRunner.scriptThread:16666 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-14 11:12:54,993 INFO    ScriptRunner.scriptThread:16666 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-14 11:12:54,994 ERROR   ScriptRunner.scriptThread:16666 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2021-05-14 11:12:54,997 INFO    ScriptRunner.scriptThread:16666 [wandb_init.py:init():546] run started, returning control to user process
2021-05-14 11:15:53,591 INFO    MainThread:16666 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-14 11:15:53,592 INFO    MainThread:16666 [wandb_run.py:_restore():1507] restore
2021-05-14 11:15:53,792 INFO    MainThread:16666 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 737
  total_bytes: 737
}

2021-05-14 11:15:54,112 INFO    MainThread:16666 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 737
  total_bytes: 4846
}

2021-05-14 11:15:54,239 INFO    MainThread:16666 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 737
  total_bytes: 4846
}

2021-05-14 11:15:54,342 INFO    MainThread:16666 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 737
  total_bytes: 4846
}

2021-05-14 11:15:54,445 INFO    MainThread:16666 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4846
  total_bytes: 4846
}

2021-05-14 11:15:54,551 INFO    MainThread:16666 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4846
  total_bytes: 4846
}

2021-05-14 11:15:54,658 INFO    MainThread:16666 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4846
  total_bytes: 4846
}

2021-05-14 11:15:54,766 INFO    MainThread:16666 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4846
  total_bytes: 4846
}

2021-05-14 11:15:54,873 INFO    MainThread:16666 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4846
  total_bytes: 4846
}

2021-05-14 11:15:56,329 INFO    MainThread:16666 [wandb_run.py:_show_files():1879] logging synced files
